### ISSUE TITLE
if use sametime morgan for express error Cannot read property 'remoteAddress' of undefined

### ISSUE THREAD

**Issue by serkandyck** [Helidium/Mitol#15]
im trying mitol with express but if using morgan logger express try remote access or something here error report:
Cannot read property 'remoteAddress' of undefined

TypeError: Cannot read property 'remoteAddress' of undefined
    at forwarded (/mnt/c/Users/x0nim/Desktop/workspace/avukat-node/node_modules/forwarded/index.js:31:35)
    at alladdrs (/mnt/c/Users/x0nim/Desktop/workspace/avukat-node/node_modules/proxy-addr/index.js:57:15)
    at proxyaddr (/mnt/c/Users/x0nim/Desktop/workspace/avukat-node/node_modules/proxy-addr/index.js:231:15)
    at IncomingMessage.ip (/mnt/c/Users/x0nim/Desktop/workspace/avukat-node/node_modules/express/lib/request.js:351:10)
    at getip (/mnt/c/Users/x0nim/Desktop/workspace/avukat-node/node_modules/morgan/index.js:466:14)
    at logger (/mnt/c/Users/x0nim/Desktop/workspace/avukat-node/node_modules/morgan/index.js:107:26)
    at Layer.handle [as handle_request] (/mnt/c/Users/x0nim/Desktop/workspace/avukat-node/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/mnt/c/Users/x0nim/Desktop/workspace/avukat-node/node_modules/express/lib/router/index.js:317:13)
    at /mnt/c/Users/x0nim/Desktop/workspace/avukat-node/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/mnt/c/Users/x0nim/Desktop/workspace/avukat-node/node_modules/express/lib/router/index.js:335:12)

**Comment by 7elven** [comment]
same problem

**Comment by splitice** [comment]
The connection property is missing on the request object
