### ISSUE TITLE
Koa compatibility?

### ISSUE THREAD

**Issue by Akkuma** [Helidium/Mitol#4]
I'm running an ultra simple server with koa and I'm seeing this

```
  TypeError: x.ee.removeListener is not a function
      at cleanup (/Users/omni/Documents/git/drive-proxy/node_modules/ee-first/index.js:62:12)
      at callback (/Users/omni/Documents/git/drive-proxy/node_modules/ee-first/index.js:54:5)
      at onevent (/Users/omni/Documents/git/drive-proxy/node_modules/ee-first/index.js:93:5)
      at respond (/Users/omni/Documents/git/drive-proxy/node_modules/koa/lib/application.js:229:43)
      at handleResponse (/Users/omni/Documents/git/drive-proxy/node_modules/koa/lib/application.js:134:36)
      at <anonymous>

fish: 'node index' terminated by signal SIGSEGV (Address boundary error)
```

Here is what I'm running
```js
const mitol = require('mitol');
const Koa = require('koa');
const app = new Koa();

// response
app.use(ctx => {
  ctx.status = 200;
  ctx.body = 'Hello';
});

mitol.createServer(app.callback()).listen(3000);
```

This works without fail when I'm using `http` as normal

**Comment by Helidium** [comment]
Hi @Akkuma, thank you for posting the issue. I have published a new version with method implemented. Now it should run Koa apps.

Keep in mind, not all methods are currently implemented.

Thank you,
